apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter-service
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: counter-service
  template:
    metadata:
      labels:
        app: counter-service
    spec:
      containers:
      - name: counter-service
        image: <IMAGE_NAME>
        ports:
        - containerPort: 80

