apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: counter-service
  namespace: default
spec:
  ipAddressType: ipv4
  serviceRef:
    name: counter-service
    port: 80
  targetGroupARN: arn:aws:elasticloadbalancing:eu-central-1:045360881194:targetgroup/counter-service/945aab2007a20318
  targetType: ip

