apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: counter-service
  namespace: counter-service
spec:
  ipAddressType: ipv4
  serviceRef:
    name: counter-service
    port: 80
  targetGroupARN: <TARGET_GROUP_ARN>
  targetType: ip

