name: Deploy Counter Service

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Build and push Docker image
      env:
        IMAGE_TAG: v1
      run: |
        docker build -t registry-1.docker.io/omerav10/counter-service:$IMAGE_TAG .
        docker push registry-1.docker.io/omerav10/counter-service:$IMAGE_TAG

    - name: Configure kubectl
      run: aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }} --region eu-central-1

    - name: Deploy to EKS
      env:
        IMAGE_TAG: v1
      run: |
        sed -i "s|<IMAGE_NAME>|registry-1.docker.io/omerav10/counter-service:$IMAGE_TAG|g" k8s/deployment.yaml
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml





