name: Deploy Counter Service

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Build and push Docker image
      env:
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/counter-service:$IMAGE_TAG .
        docker push ${{ secrets.DOCKER_USERNAME }}/counter-service:$IMAGE_TAG

    - name: Configure kubectl
      run: aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }} --region eu-central-1

    - name: Deploy to EKS
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        sed -i "s|<DOCKER_USERNAME>|$DOCKER_USERNAME|g" k8s/deployment.yaml
        sed -i "s|<IMAGE_TAG>|$IMAGE_TAG|g" k8s/deployment.yaml
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml

