name: List EKS Clusters

on:
  push:
    branches:
      - main

jobs:
  list-clusters:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: List EKS clusters
      run: aws eks list-clusters

    - name: Configure kubectl
      run: aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }} --region eu-central-1

    - name: List nodes in the EKS cluster
      run: kubectl get nodes
