name: List EKS Clusters

on:
  push:
    branches:
      - main

jobs:
  list-clusters:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2


    - name: List EKS clusters
      run: aws eks list-clusters

